---
  - hosts: trackers
    vars_files:
      - vars/secrets.yml
      - vars/blacklist.yml
    roles:
      - basicshit
      - role: jnv.unattended-upgrades
        unattended_main: sre@janky.solutions
      - opentracker
      - munin-node
