---
  - name: Install munin-node
    apt: name=munin-node state=installed

  - name: Configure munin-node
    template: src=munin-node.conf.j2 dest=/etc/munin/munin-node.conf
    notify:
      - Restart munin-node
