---
  - name: Install munin-node and depends
    apt: name={{ item }} state=installed
    with_items:
      - munin-node
      - liblwp-useragent-determined-perl

  - name: Configure munin-node
    template: src=munin-node.conf.j2 dest=/etc/munin/munin-node.conf
    notify:
      - Restart munin-node

  - name: Install opentracker plugin
    template: src=opentracker_ dest=/usr/share/munin/plugins/opentracker_ mode=a+x
    notify:
      - Restart munin-node

  - name: Configure opentracker plugin
    template: src=opentracker.conf dest=/etc/munin/plugin-conf.d/opentracker
    notify:
      - Restart munin-node

  - name: Activate opentracker plugin
    file: state=link src=/usr/share/munin/plugins/opentracker_ dest=/etc/munin/plugins/opentracker{{ item }}
    with_items:
      - v4_conn
      - v4_scrp
      - v4_syncs
      - v4_tcp
      - v4_torr
      - v4_udp
      - v6_conn
      - v6_scrp
      - v6_syncs
      - v6_tcp
      - v6_torr
      - v6_udp
    notify:
      - Restart munin-node

  - name: Allow munin master to access this munin-node
    ufw: rule=allow port=4949 from_ip="{{ item.ip }}"
    with_items: "{{ munin_masters }}"
