---
  - name: Update packages
    apt: upgrade=full update_cache=yes

  - name: Install useful things from the debian repos
    apt: name={{ item }} state=latest
    with_items:
      - htop
      - mosh
      - tmux
      - ufw
      - git
      - xtail
      - zsh
      - python-pip
      - python-dev
      - python-psutil
      - python-virtualenv

  - name: Install some useful things from pypi
    pip: name={{ item }} state=latest
    with_items: [thefuck]

  - include: ohmyzsh.yml

  - name: Add SSH keys
    authorized_key: key={{ item }} user=root
    when: ssh_keys is defined
    with_items: "{{ ssh_keys }}"
