---
  - name: Update packages
    apt: upgrade=full update_cache=yes

  - name: Install useful things from the debian repos
    apt: name={{ item }} state=latest
    with_items:
      - htop
      - mosh
      - tmux
      - ufw
      - git
      - xtail
      - zsh
      - python-pip
      - python-dev
      - python-psutil
      - python-virtualenv

  - name: Install some useful things from pypi
    pip: name={{ item }} state=latest
    with_items: [thefuck]

  - include: ohmyzsh.yml

  - name: List all IPv4s
    run_once: true
    debug: var=hostvars[item].ansible_default_ipv4.address
    with_items: "{{ groups['trackers'] }}"

  - name: List all IPv6s
    run_once: true
    debug: var=hostvars[item].ansible_default_ipv6.address
    with_items: "{{ groups['trackers'] }}"
