---
  - name: Make trackers
    digital_ocean:
      state: present
      command: droplet
      name: "{{ item }}.tracker.janky.solutions"
      unique_name: yes
      api_token: "{{ digital_ocean_token }}"
      size_id: 512mb
      ipv6: yes
      private_networking: yes
      ssh_key_ids: "{{ do_ssh_keys }}"
      region_id: "{{ item }}"
      image_id: debian-8-x64
      wait_timeout: 500
    register: trackers
    with_items:
      # - ams2
      # - ams3
      - blr1
      # - fra1
      - lon1
      - nyc1
      # - nyc2
      # - nyc3
      # - sfo1
      - sfo2
      - sgp1
      # - tor1

  - name: Setup IPv4 DNS records
    digital_ocean_domain:
      state: present
      name: "{{ item.droplet.name }}"
      ip: "{{ item.droplet.ip_address }}"
      api_token: "{{ digital_ocean_token }}"
    with_items: "{{ trackers.results }}"

  # - name: Setup IPv6 DNS records
  #   digital_ocean_domain:
  #     state: present
  #     name: "{{ item.droplet.name }}"
  #     ip: "{{ item.droplet.networks.v6[0].ip_address }}"
  #     api_token: "{{ digital_ocean_token }}"
  #   with_items: "{{ trackers.results }}"

  - name: Add trackers to our play
    add_host:
      hostname: "{{ item.droplet.name }}"
      ansible_ssh_host: "{{ item.droplet.ip_address }}"
      ansible_ssh_user: "root"
      groups: trackers
      do_metadata: "{{ item }}"
    with_items: "{{ trackers.results }}"
    changed_when: false

  - name: Make monitoring boxes
    digital_ocean:
      state: present
      command: droplet
      name: "tracker-monitoring.janky.solutions"
      unique_name: yes
      api_token: "{{ digital_ocean_token }}"
      size_id: 512mb
      ipv6: yes
      private_networking: yes
      ssh_key_ids: "{{ do_ssh_keys }}"
      region_id: sfo2
      image_id: debian-8-x64
      wait_timeout: 500
    register: monitoring

  - name: Add monitoring box to our play
    add_host:
      hostname: "{{ monitoring.droplet.name }}"
      ansible_ssh_host: "{{ monitoring.droplet.ip_address }}"
      ansible_ssh_user: "root"
      groups: monitoring
      do_metadata: "{{ monitoring }}"
    changed_when: false
